APP_PASSWORD="AsdfghjkL!!2025"

SUPABASE_URL="https://iqdducdbkoqbhcbtmdff.supabase.co"
SUPABASE_SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZGR1Y2Ria29xYmhjYnRtZGZmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTg5OTA0MiwiZXhwIjoyMDgxNDc1MDQyfQ.pQPakkMTMSuXoOR2B5yTB_HzX-NYmUK7LJt_S2VQFqQ"
DATABASE_URL="postgresql://postgres:[YOUR-PASSWORD]@db.iqdducdbkoqbhcbtmdff.supabase.co:5432/postgres"
SUPABASE_BUCKET="evidence"
